#!/bin/bash

APP="$1"
IMAGE="dokku/$APP"

read -d '' runner <<'EOF'
profile_dir=/app/.profile.d;
from=\$profile_dir/app-env.sh;
to=\$profile_dir/\~app-env.sh;
if [[ -f \$from ]]; then
  cp \$from \$to;
  chmod +x \$to;
fi
EOF

set -e

echo "-----> Adding priotized app-env.sh ..."
id=$(echo $runner | docker run -i -a stdin $IMAGE /bin/bash -)
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
